adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),


    path('products/create/category/<int:pk>', adminapp.product_create, name='product_create'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/category/<int:pk>/', adminapp.products, name='products'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit', authapp.edit, name='edit'),
    path('register', authapp.register, name='register')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>', basketapp.basket_add, name='add'),
    path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('about/', mainapp.about, name='about'),
    path('faqs/', mainapp.faqs, name='faqs'),
    # path('shoppingcart/', mainapp.shoppingcart, name='shoppingcart'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('checkout', mainapp.checkout, name='checkout'),
    # path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('productdetail/<int:id>/', mainapp.productdetail, name='productdetail')
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=50, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    is_active = models.BooleanField(verbose_name='Активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название', max_length=200, unique=True)
    short_desc = models.CharField(verbose_name='Краткое описание продукта', max_length=100, blank=True)
    description = models.TextField(verbose_name='Описание продукта', blank=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=8, decimal_places=2, default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
import json

from basketapp.models import Basket
from .models import Product, ProductCategory


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def main(request):
    # with open('static/file_to_load.json') as file:
    #     data_product = json.load(file)
    new_product = Product.objects.all().order_by('id')[:4]
    popular_product = Product.objects.all().order_by('-price')[:4]
    basket = get_basket(request.user)

    # with open('static/file_to_load_categories.json') as file:
    #     data_category = json.load(file)
    data_category = ProductCategory.objects.filter(is_active=True)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Main',
        'new_products': new_product,
        'popular_product': popular_product,
        'categories': data_category,
        'basket': basket,
        'links': data_links
    }
    return render(request, 'mainapp/index.html', context=content)


def products(request, pk=None, page=1):
    basket = get_basket(request.user)

    # Если в урле задан идентификатор категории, то необходимо фильтрануть товары по категории,
    # иначе выводим все товары
    if pk is not None:
        if pk == 0:
            data_product = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            current_category = {'name': 'Все игрушки',
                                'pk': 0}
        else:
            current_category = get_object_or_404(ProductCategory, pk=pk)
            data_product = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            # data_product = Product.objects.all()
    else:
        data_product = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        current_category = {'name': 'Все игрушки',
                            'pk': 0}

    data_category = ProductCategory.objects.filter(is_active=True)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    paginator = Paginator(data_product, 1)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    page_range = paginator.get_elided_page_range(number=page)
    print(data_product)
    content = {
        'title': 'Products',
        'products': products_paginator,
        'page_range': page_range,
        'categories': data_category,
        'current_category': current_category,
        'basket': basket,
        'links': data_links
    }
    return render(request, 'mainapp/products.html', context=content)


def productdetail(request, id):
    basket = get_basket(request.user)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    if id is not None or id == 0:
        if id == 0:
            data_category = ProductCategory.objects.filter(is_active=True)
            data_product = Product.objects.all()
            current_category = {'name': 'Все игрушки'}

            content = {
                'title': 'Products',
                'products': data_product,
                'categories': data_category,
                'current_category': current_category,
                'basket': basket,
                'links': data_links
            }
            return render(request, 'mainapp/products.html', context=content)
        else:
            product = get_object_or_404(Product, pk=id)
            current_category = product.category.name
    else:
        data_category = ProductCategory.objects.filter(is_active=True)
        data_product = Product.objects.all()
        current_category = {'name': 'Все игрушки'}

        content = {
            'title': 'Products',
            'products': data_product,
            'categories': data_category,
            'current_category': current_category,
            'basket': basket,
            'links': data_links
        }
        return render(request, 'mainapp/products.html', context=content)

    data_category = ProductCategory.objects.filter(is_active=True)

    # В качестве рекоммендуемых берем простова товары из той же категории что и просматриваемый товар
    recommend_products = Product.objects.filter(category__pk=product.category.pk).exclude(pk=product.pk)

    content = {
        'title': 'ProductDetail',
        'product': product,
        'recommend_products': recommend_products,
        'categories': data_category,
        'current_category': current_category,
        'basket': basket,
        'links': data_links
    }

    return render(request, 'mainapp/productdetail.html', context=content)


def contact(request):
    data_category = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Contact',
        'links': data_links,
        'categories': data_category,
        'basket': basket,
    }
    return render(request, 'mainapp/contact.html', context=content)


def about(request):
    basket = get_basket(request.user)

    data_category = ProductCategory.objects.filter(is_active=True)
    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'About',
        'links': data_links,
        'categories': data_category,
        'basket': basket,
    }
    return render(request, 'mainapp/about.html', context=content)


def faqs(request):
    # with open('static/file_to_load.json') as file:
    #     data_product = json.load(file)
    popular_product = Product.objects.all().order_by('-price')[:4]
    data_category = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'FAQs',
        'popular_product': popular_product,
        'categories': data_category,
        'links': data_links,
        'basket': basket,
    }
    return render(request, 'mainapp/faqs.html', context=content)


def shoppingcart(request):
    # with open('static/file_to_load.json') as file:
    #     data_product = json.load(file)
    data_product = Product.objects.all()
    popular_product = Product.objects.all().order_by('-price')[:4]
    basket = get_basket(request.user)

    # with open('static/file_to_load_categories.json') as file:
    #     data_category = json.load(file)
    data_category = ProductCategory.objects.filter(is_active=True)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'ShoppingCart',
        'products': data_product,
        'popular_product': popular_product,
        'categories': data_category,
        'links': data_links,
        'basket': basket,
    }
    return render(request, 'mainapp/shoppingcart.html', context=content)


def checkout(request):
    basket = get_basket(request.user)
    data_category = ProductCategory.objects.filter(is_active=True)
    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Checkout',
        'links': data_links,
        'categories': data_category,
        'basket': basket,
    }
    return render(request, 'mainapp/checkout.html', content)

mainapp/templates/mainapp/includes/inc_footer.html
{% load static %}
<div id="tooplate_bottom_wrapper">
    <div id="tooplate_bottom">
        <div class="col col_4">
            <h4>Information</h4>
            <ul class="list_bullet">
                <li><a href="#">Consectetur adipiscing eli</a></li>
                <li><a href="#">Nullam vulputate est</a></li>
                <li><a href="#">Duis porta velit</a></li>
                <li><a href="#">Pretium suscipit</a></li>
                <li><a href="#">Nullam eu diam</a></li>
                <li><a href="#">Duis in libero est</a></li>
            </ul>
        </div>
        <div class="col col_4">
            <h4>Services &amp; Support</h4>
            <ul class="list_bullet">
                <li><a href="#">Duis porta velit</a></li>
                <li><a href="#">Pretium suscipit</a></li>
                <li><a href="#">Nullam eu diam</a></li>
                <li><a href="#">Duis in libero est</a></li>
                <li><a href="#">Aenean tincidunt</a></li>
                <li><a href="#">Morbi tempus iaculis</a></li>
            </ul>
        </div>
        <div class="col col_4 twitter">
            <h4>Pages</h4>
            <ul class="list_bullet">
                <li><a href="{% url 'main' %}">Home</a></li>
                <li><a href="{% url 'products:index' %}">Products</a></li>
                <li><a href="{% url 'about' %}" class="selected">About</a></li>
                <li><a href="{% url 'faqs' %}">FAQs</a></li>
                <li><a href="{% url 'contact' %}" class="last">Contact</a></li>
            </ul>


        </div>
        <div class="col col_4">
            <h4>Newsletter</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <div id="tooplate_newsletter">
                <form action="#" method="get">
                    <input type="text" value=" " name="keyword" id="keyword" title="keyword" onfocus="clearText(this)"
                           onblur="clearText(this)" class="txt_field"/>
                    <input type="submit" name="Search" value=" " alt="Search" id="searchbutton" title="Search"
                           class="sub_btn"/>
                </form>
            </div>
            <div class="clear h30"></div>
            <a href="#"><img src="{% static 'img/facebook.png' %}" alt="Facebook"/></a>
            <a href="#"><img src="{% static 'img/google.png' %}" alt="Google"/></a>
            <a href="#"><img src="{% static 'img/skype.png' %}" alt="Skype"/></a>
            <a href="#"><img src="{% static 'img/twitter2.png' %}" alt="Twitter"/></a>
        </div>
        <div class="clear"></div>
    </div> <!-- END of bottom -->
</div> <!-- END of bottom wrapper -->

<div id="tooplate_footer_wrapper">
    <div id="tooplate_footer">
        Copyright © {% now "Y" %} Shumka Shop
    </div> <!-- END of footer -->
</div> <!-- END of footer wrapper -->

mainapp/templates/mainapp/includes/inc_header.html
{% load static %}
<div id="tooplate_header">
    <div id="header_top">
        <div id="site_title"><a href="/">Clothing Template</a></div>
        <div id="tooplate_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}
                        selected
                      {% endif %}">Главная</a></li>
                <li>
                    <a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.namespace == 'products' %}
              selected
            {% endif %}">Продукция</a>
                    <ul>
                        {% for category in categories %}
                        <li><a href="{% url 'products:category' category.id %}" class="{% if category.name == current_category.name %}
              selected
            {% endif %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}
                        selected
                      {% endif %}">О нас</a></li>
<!--                <li><a href="{% url 'faqs' %}" class="{% if request.resolver_match.url_name == 'faqs' %}-->
<!--                        selected-->
<!--                      {% endif %}">FAQs</a></li>-->
                <li><a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}
                        selected
                      {% endif %}">Контакты</a></li>
                {% if user.is_superuser %}
                <li><a href="{% url 'adminapp:users' %}">Админка</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'auth:edit' %}">{{ user.first_name|default:'Юзер' }}</a></li>
                {% endif %}
                <li>
                    {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">Выйти</a>
                    {% else %}
                    <a href="{% url 'auth:login' %}">Войти</a>
                    {% endif %}
                </li>
            </ul>
            <br style="clear: left"/>
        </div> <!-- end of tooplate_menu -->
    </div> <!-- END of header top -->

    <div id="header_bottom">
        <p>
            <a href="{% url 'basket:view' %}">Корзина</a> |
            <a href="{% url 'checkout' %}">Купить</a> |
            <span>Товаров в корзине (
                {% if basket %}
                    {{ basket.0.total_quantity }}
                {% endif %}
                )</span>
                {% if basket %}
                <span> на сумму:{{ basket.0.total_cost|floatformat:0 }} руб.</span>
                {% endif %}
        </p>

        <div id="tooplate_search">
            <form action="#" method="get">
                <input type="text" value=" " name="keyword" id="keyword" title="keyword" onfocus="clearText(this)"
                       onblur="clearText(this)" class="txt_field"/>
                <input type="submit" name="Search" value=" " alt="Поиск" id="searchbutton" title="Поиск"
                       class="sub_btn"/>
            </form>
        </div>
    </div> <!-- END of header bottom -->
</div> <!-- END of header -->

mainapp/templates/mainapp/includes/inc_popular_products.html
{% load static %}
{% load my_tags %}
<div id="sidebar">
        <div class="sidebar_section sidebar_section_bg">
            <h3>Популярные товары</h3>
            <ul class="sidebar_link_list popular_products">
                {% for product in popular_product %}
                <li>
                    <img src="{{ product.image|media_folder_products }}" align="{{ product.short_desc}}" height="40px"/>
                    <span class="title"><a href="{% url 'products:productdetail' product.id %}">{{ product.name|upper }}</a></span>
                    <span class="price">${{ product.price }}</span>
                    <span class="clear"></span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>