authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit', authapp.edit, name='edit'),
    path('register', authapp.register, name='register')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>', basketapp.basket_add, name='add'),
    path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('about/', mainapp.about, name='about'),
    path('faqs/', mainapp.faqs, name='faqs'),
    # path('shoppingcart/', mainapp.shoppingcart, name='shoppingcart'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('checkout', mainapp.checkout, name='checkout'),
    # path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('productdetail/<int:id>/', mainapp.productdetail, name='productdetail')
]

basketapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='Время добавления', auto_now_add=True)

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    def total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
import json

from django.template.loader import render_to_string
from django.urls import reverse

from basketapp.models import Basket
from mainapp.models import ProductCategory, Product


@login_required
def basket(request):
    popular_product = Product.objects.all().order_by('-price')[:4]
    data_category = ProductCategory.objects.all()
    count_basket_products = get_count_products_in_basket(request)
    basket_products = []
    basket_summ = 0

    if request.user.is_authenticated:
        basket_products = Basket.objects.filter(user=request.user).order_by('product__category')
        basket_summ = sum(bask.quantity * bask.product.price for bask in basket_products)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Корзина',
        'popular_product': popular_product,
        'basket_products': basket_products,
        'categories': data_category,
        'count_basket_products': count_basket_products,
        'basket_summ': basket_summ,
        'links': data_links
    }
    return render(request, 'basketapp/shoppingcart.html', content)


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:productdetail', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket = get_object_or_404(Basket, pk=pk)

    if basket:
        basket.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_products = Basket.objects.filter(user=request.user). \
            order_by('product__category')

        basket_summ = sum(bask.quantity * bask.product.price for bask in basket_products)

        content = {
            'basket_products': basket_products,
            'basket_summ': basket_summ,
        }

        result = render_to_string('basketapp/includes/inc_basket_list.html', \
                                  content)

        return JsonResponse({'result': result})


def get_count_products_in_basket(request):
    # Товары в корзине, отображаем количество в хэдере
    count_basket_products = 0

    if request.user.is_authenticated:
        count_basket_products = len(Basket.objects.filter(user=request.user))

    return count_basket_products

basketapp/templates/basketapp/includes/inc_basket_list.html
{% load mainapp_extras %}
{% load static %}
{% load my_tags %}

<h1>Товары в корзине</h1>

<table width="580px" cols="0" cellspacing="0" cellpadding="5">
    <tr bgcolor="#ddd">
        <th width="220" align="left">Изображение</th>
        <th width="180" align="left">Название</th>
        <th width="160" align="center">Кол-во</th>
        <th width="60" align="right">Цена</th>
        <th width="60" align="right">Сумма</th>
        <th width="90"></th>

    </tr>
    {% for basket in basket_products %}

    <tr>
        <td><a href="{% url 'products:productdetail' basket.product.id %}"><img src="{{ basket.product.image|media_folder_products }}"
                                                                                alt="{{basket.product.name}}"
                                                                                height="70px"/></a></td>
        <td><a href="{% url 'products:productdetail' basket.product.id %}">{{ basket.product.name|upper }}</a></td>
        <td align="center">
            <input type="number" name="{{basket.pk}}" value="{{basket.quantity}}" min="0" style="width: 40px; text-align: right"/>
        </td>
        <td align="right">${{ basket.product.price }}</td>
        <td align="right">${% multiply basket.quantity basket.product.price %}</td>
        <td align="center"><a href="{% url 'basket:remove' basket.id%}"><img src="{% static 'img/remove.png' %}"
                                                                             alt="remove"/><br/>Удалить</a>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="3" style="background: url({% static 'img/tooplate_h2.png' %}) repeat" align="right"
            height="30px">Have
            you modified your basket? Please click here to <a
                    href="{% url 'basket:view' %}"><strong>Update</strong></a>&nbsp;&nbsp;
        </td>
        <td align="right" style="background: url({% static 'img/tooplate_h2.png' %}) repeat; font-weight:bold">
            Сумма корзины
        </td>
        <td align="right" style="background: url({% static 'img/tooplate_h2.png' %}) repeat; font-weight:bold">
            ${{basket_summ}}
        </td>
        <td style="background: url({% static 'img/tooplate_h2.png' %}) repeat; font-weight:bold"></td>
    </tr>
</table>
<p class="right"><a href="checkout.html" class="button">checkout</a></p>