adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),


    path('products/create/category/<int:pk>', adminapp.product_create, name='product_create'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/category/<int:pk>/', adminapp.products, name='products'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit', authapp.edit, name='edit'),
    path('register', authapp.register, name='register')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('about/', mainapp.about, name='about'),
    path('faqs/', mainapp.faqs, name='faqs'),
    # path('shoppingcart/', mainapp.shoppingcart, name='shoppingcart'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('checkout', mainapp.checkout, name='checkout'),
    # path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.list import ListView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


@user_passes_test(lambda u: u.is_superuser)
def users(request):
    title = 'Админка: пользователи'

    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
    content = {
        'title': title,
        'objects': users_list
    }
    return render(request, 'adminapp/users.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'Пользователи/Создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:users'))
    else:
        user_form = ShopUserRegisterForm()

    content = {
        'title': title,
        'update_form': user_form
    }
    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'Пользователи/Редактирование'
    edit_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    content = {
        'title': title,
        'update_form': edit_form
    }
    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'Пользователи/Удаление'
    user_to_delete = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user_to_delete.is_active = False if user_to_delete.is_active else True
        user_to_delete.save()
        return HttpResponseRedirect(reverse('adminapp:users'))

    content = {
        'title': title,
        'user_to_delete': user_to_delete
    }
    return render(request, 'adminapp/user_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'Категории/Создание'

    if request.method == 'POST':
        category_form = ProductCategoryEditForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('adminapp:categories'))
    else:
        category_form = ProductCategoryEditForm()

    content = {
        'title': title,
        'update_form': category_form
    }
    return render(request, 'adminapp/category_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'Админка: Категории'
    categories_list = ProductCategory.objects.all().order_by('-is_active', 'name')

    content = {
        'title': title,
        'objects': categories_list
    }
    return render(request, 'adminapp/categories.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'Категории/Редактирование'
    edit_category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:category_update', args=[edit_category.pk]))
    else:
        edit_form = ProductCategoryEditForm(instance=edit_category)

    content = {
        'title': title,
        'update_form': edit_form
    }
    return render(request, 'adminapp/category_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'Категории/Удаление'
    category_to_delete = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        category_to_delete.is_active = False if category_to_delete.is_active else True
        category_to_delete.save()
        return HttpResponseRedirect(reverse('adminapp:categories'))

    content = {
        'title': title,
        'category_to_delete': category_to_delete
    }
    return render(request, 'adminapp/category_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'Товар/Создание'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('adminapp:products', args=[pk]))
    else:
        product_form = ProductEditForm(initial={'category': category})

    content = {
        'title': title,
        'update_form': product_form
    }
    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = "Админка: Товары"
    category = get_object_or_404(ProductCategory, pk=pk)
    product_list = Product.objects.filter(category__pk=category.pk).order_by('name')

    content = {
        'title': title,
        'category': category,
        'objects': product_list
    }
    return render(request, 'adminapp/products.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_read(request, pk):
    title = "Админка: Товары"
    category = get_object_or_404(ProductCategory, pk=pk)
    product_list = Product.objects.filter(category__pk=category.pk).order_by('name')

    content = {
        'title': title,
        'category': category,
        'objects': product_list
    }
    return render(request, 'adminapp/product_read.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'Товар/Редактирование'
    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {
        'title': title,
        'category': edit_product.category,
        'update_form': edit_form
    }
    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title = 'Товар/Удаление'
    product_to_delete = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product_to_delete.is_active = False if product_to_delete.is_active else True
        product_to_delete.save()
        return HttpResponseRedirect(reverse('adminapp:categories'))

    content = {
        'title': title,
        'product_to_delete': product_to_delete
    }
    return render(request, 'adminapp/product_delete.html', content)


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории/создание'

        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории/редактирование'

        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории/удаление'

        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False if self.object.is_active else True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Товар/описание'
        print(context['object'])
        return context

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title|title}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
  <div class="container">
    <div class="h2 text-center head">
      Админка: {{title|title}}
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
      <a href="{% url 'adminapp:category_create' %}" class="btn btn-primary">
        новая категория
      </a>
      <br>
      <br>
    {% for object in objects %}
      <div class="category_record"
      {% if not object.is_active %}
           style="opacity: 0.5"
      {% endif %}>
        <div class="category_name">
          <strong>{{ object.name|upper }}</strong>
        </div>
        <div class="category_actions">
            <a href="{% url 'adminapp:products' object.pk %}" class="btn btn-primary">
              товары категории
            </a>
            <a href="{% url 'adminapp:category_update' object.pk %}" class="btn btn-warning">
              редактировать
            </a>
            <a href="{% url 'adminapp:category_delete' object.pk %}" class="btn
            {% if object.is_active %}
                btn-danger
            {% else %}
                btn-success
            {% endif %}">
                {% if object.is_active %}
                    деактивировать
                {% else %}
                    активировать
                {% endif %}
            </a>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>

    <hr>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите
    {% if object.is_active%}
      деактивировать
    {% else %}
      активировать
    {% endif %}
    категорию {{ object.name }}?
    <form action="{% url 'adminapp:category_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="{% if object.is_active %}
деактивировать{% else %}
активировать{% endif %}">
    </form>
      <a href="{% url 'adminapp:categories' %}" class="btn btn-success">
        Отмена
      </a>
  </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control btn btn-primary" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите
    {% if product_to_delete.is_active%}
      деактивировать
    {% else %}
      активировать
    {% endif %}
    категорию {{ product_to_delete.name }}?
    <form action="{% url 'adminapp:product_delete' product_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="{% if product_to_delete.is_active %}
деактивировать{% else %}
активировать{% endif %}">
    </form>
      <a href="{% url 'adminapp:categories' %}" class="btn btn-success">
        Отмена
      </a>
  </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="product">
    <div class="col col_2 product_preview">
        <a rel="lightbox" href="/media/{{ product.image.url }}"><img src="/media/{{product.image}}"
                                                                     class="left" alt="{{product.name}}" width="200px"/></a>
        <div class="clear"></div>
    </div>
    <div class="col col_2 product_detail">
        <h1>Название: {{ product.name}}</h1>
        <p><em>Краткое описание: {{product.short_desc}}</em></p>
        <p>Описание:{{product.description}}</p>
        <div class="clear h20"></div>
        <p class="price">Цена: ${{product.price}}</p>
        <div class="clear h20"></div>
        <p class="add_to_cart">На складе: <strong>{{product.quantity}}</strong></p>
    </div>
    <div class="product_actions">
        <a href="{% url 'adminapp:product_update' product.pk %}" class="btn btn-warning">
            редактировать
        </a>
        <a href="{% url 'adminapp:product_delete' product.pk %}" class="btn
            {% if object.is_active %}
                btn-danger
            {% else %}
                btn-success
            {% endif %}">
            {% if object.is_active %}
            деактивировать
            {% else %}
            активировать
            {% endif %}
        </a>
    </div>
    <div class="clear"></div>
</div>
<button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:categories' %}">
        к списку товаров
    </a>
</button>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control btn btn-primary" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:categories' %}">
      к списку товаров
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="products_list">
      <a href="{% url 'adminapp:product_create' category.pk %}">
        новый продукт
      </a>
      <br>
      <br>
    {% for object in objects %}
      <div class="product_record"
      {% if not object.is_active %}
           style="opacity: 0.5"
      {% endif %}>
        <img
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}" width="100px">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
            <a href="{% url 'adminapp:product_read' object.pk %}" class="btn btn-primary">
              подробнее
            </a>
            <a href="{% url 'adminapp:product_update' object.pk %}" class="btn btn-warning">
              редактировать
            </a>
            <a href="{% url 'adminapp:product_delete' object.pk %}" class="btn
            {% if object.is_active %}
                btn-danger
            {% else %}
                btn-success
            {% endif %}">
               {% if object.is_active %}
                    деактивировать
                {% else %}
                    активировать
                {% endif %}
            </a>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
      <hr>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите {% if user_to_delete.is_active %}деактивировать{% else %}активировать{% endif %} {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'adminapp:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="{% if user_to_delete.is_active %}деактивировать{% else %}активировать{% endif %}">
    </form>
      <a href="{% url 'adminapp:users' %}" class="btn btn-success">
        Отмена
      </a>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control btn btn-primary" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="users_list">
    <a href="{% url 'adminapp:user_create' %}" class="btn btn-primary">
        новый пользователь
    </a>
    <br>
    <br>
    <br>
    {% for object in object_list %}
    <div class="user_record" {% if not object.is_active %}style="opacity: 0.5"{% endif %}>
        <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
             alt="{{ object.username }}" width="100px">
        <div class="user_role"><strong>Роль: </strong>
            {% if object.is_superuser %}
            администратор
            {% else %}
            пользователь
            {% endif %}
            <a href="{% url 'adminapp:user_update' object.pk %}" class="btn btn-warning">
                редактировать
            </a>
            <a href="{% url 'adminapp:user_delete' object.pk %}" class="btn
            {% if object.is_active %}
              btn-danger
            {% else %}
              btn-success
            {% endif %}">
                {% if object.is_active %}
                деактивировать
                {% else %}
                активировать
                {% endif%}
            </a>
        </div>
        <div class="user_name">
            <p><strong>{{ object.username }}</strong></p>
            <p>
                {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
            <p>{{ object.last_name|title }}</p>
            {% endif %}
            {% endif %}
            </p>
        </div>
        <div class="user_age">
            <strong>age:</strong>
            {{ object.age }} лет
        </div>
        <div class="user_email">
            <strong>email:</strong>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            <strong>logged:</strong>
            {{ object.last_login }}
        </div>
        <div class="user_is_active">
            <strong>is_active:</strong>
            {{ object.is_active }}
        </div>
    </div>
    <hr>
    {% endfor%}
</div>
{% endblock %}