authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit', authapp.edit, name='edit'),
    path('register', authapp.register, name='register')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>', basketapp.basket_add, name='add'),
    path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('about/', mainapp.about, name='about'),
    path('faqs/', mainapp.faqs, name='faqs'),
    # path('shoppingcart/', mainapp.shoppingcart, name='shoppingcart'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('checkout', mainapp.checkout, name='checkout'),
    # path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('productdetail/<int:id>/', mainapp.productdetail, name='productdetail')
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=50, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    is_active = models.BooleanField(verbose_name='Активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название', max_length=200, unique=True)
    short_desc = models.CharField(verbose_name='Краткое описание продукта', max_length=100, blank=True)
    description = models.TextField(verbose_name='Описание продукта', blank=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=8, decimal_places=2, default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
import json

from basketapp.models import Basket
from .models import Product, ProductCategory


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def main(request):
    # with open('static/file_to_load.json') as file:
    #     data_product = json.load(file)
    new_product = Product.objects.all().order_by('id')[:4]
    popular_product = Product.objects.all().order_by('-price')[:4]
    basket = get_basket(request.user)

    # with open('static/file_to_load_categories.json') as file:
    #     data_category = json.load(file)
    data_category = ProductCategory.objects.filter(is_active=True)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Main',
        'new_products': new_product,
        'popular_product': popular_product,
        'categories': data_category,
        'basket': basket,
        'links': data_links
    }
    return render(request, 'mainapp/index.html', context=content)


def products(request, pk=None, page=1):
    basket = get_basket(request.user)

    # Если в урле задан идентификатор категории, то необходимо фильтрануть товары по категории,
    # иначе выводим все товары
    if pk is not None:
        if pk == 0:
            data_product = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            current_category = {'name': 'Все игрушки',
                                'pk': 0}
        else:
            current_category = get_object_or_404(ProductCategory, pk=pk)
            data_product = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            # data_product = Product.objects.all()
    else:
        data_product = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        current_category = {'name': 'Все игрушки',
                            'pk': 0}

    data_category = ProductCategory.objects.filter(is_active=True)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    paginator = Paginator(data_product, 1)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    page_range = paginator.get_elided_page_range(number=page)
    print(data_product)
    content = {
        'title': 'Products',
        'products': products_paginator,
        'page_range': page_range,
        'categories': data_category,
        'current_category': current_category,
        'basket': basket,
        'links': data_links
    }
    return render(request, 'mainapp/products.html', context=content)


def productdetail(request, id):
    basket = get_basket(request.user)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    if id is not None or id == 0:
        if id == 0:
            data_category = ProductCategory.objects.filter(is_active=True)
            data_product = Product.objects.all()
            current_category = {'name': 'Все игрушки'}

            content = {
                'title': 'Products',
                'products': data_product,
                'categories': data_category,
                'current_category': current_category,
                'basket': basket,
                'links': data_links
            }
            return render(request, 'mainapp/products.html', context=content)
        else:
            product = get_object_or_404(Product, pk=id)
            current_category = product.category.name
    else:
        data_category = ProductCategory.objects.filter(is_active=True)
        data_product = Product.objects.all()
        current_category = {'name': 'Все игрушки'}

        content = {
            'title': 'Products',
            'products': data_product,
            'categories': data_category,
            'current_category': current_category,
            'basket': basket,
            'links': data_links
        }
        return render(request, 'mainapp/products.html', context=content)

    data_category = ProductCategory.objects.filter(is_active=True)

    # В качестве рекоммендуемых берем простова товары из той же категории что и просматриваемый товар
    recommend_products = Product.objects.filter(category__pk=product.category.pk).exclude(pk=product.pk)

    content = {
        'title': 'ProductDetail',
        'product': product,
        'recommend_products': recommend_products,
        'categories': data_category,
        'current_category': current_category,
        'basket': basket,
        'links': data_links
    }

    return render(request, 'mainapp/productdetail.html', context=content)


def contact(request):
    data_category = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Contact',
        'links': data_links,
        'categories': data_category,
        'basket': basket,
    }
    return render(request, 'mainapp/contact.html', context=content)


def about(request):
    basket = get_basket(request.user)

    data_category = ProductCategory.objects.filter(is_active=True)
    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'About',
        'links': data_links,
        'categories': data_category,
        'basket': basket,
    }
    return render(request, 'mainapp/about.html', context=content)


def faqs(request):
    # with open('static/file_to_load.json') as file:
    #     data_product = json.load(file)
    popular_product = Product.objects.all().order_by('-price')[:4]
    data_category = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'FAQs',
        'popular_product': popular_product,
        'categories': data_category,
        'links': data_links,
        'basket': basket,
    }
    return render(request, 'mainapp/faqs.html', context=content)


def shoppingcart(request):
    # with open('static/file_to_load.json') as file:
    #     data_product = json.load(file)
    data_product = Product.objects.all()
    popular_product = Product.objects.all().order_by('-price')[:4]
    basket = get_basket(request.user)

    # with open('static/file_to_load_categories.json') as file:
    #     data_category = json.load(file)
    data_category = ProductCategory.objects.filter(is_active=True)

    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'ShoppingCart',
        'products': data_product,
        'popular_product': popular_product,
        'categories': data_category,
        'links': data_links,
        'basket': basket,
    }
    return render(request, 'mainapp/shoppingcart.html', context=content)


def checkout(request):
    basket = get_basket(request.user)
    data_category = ProductCategory.objects.filter(is_active=True)
    with open('static/file_to_load_links.json') as file:
        data_links = json.load(file)

    content = {
        'title': 'Checkout',
        'links': data_links,
        'categories': data_category,
        'basket': basket,
    }
    return render(request, 'mainapp/checkout.html', content)

mainapp/templates/mainapp/about.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
{{ title|title }}
{% endblock %}
{% block main%}
<div id="tooplate_main"><span class="main_border main_border_t"></span><span class="main_border main_border_b"></span>

    <div class="col col_2">
        <h3>About HTML CSS Template</h3>
        <p>Proin ornare euismod neque at mollis. Donec gravida magna non risus bibendum fermentum et ut turpis. Nulla
            suscipit nunc nec urna ullamcorper bibendum. Maecenas non nibh purus, vitae volutpat metus. </p>
        <p>In hendrerit leo id arcu interdum imperdiet. Aenean aliquam lectus sed arcu auctor ornare. Pellentesque
            lacinia lorem sit amet sapien condimentum tincidunt. Praesent orci sem, mollis et rhoncus nec, lacinia nec
            arcu.</p>
    </div>

    <div class="col col_2">
        <h3>Cras faucibus tempus lorem</h3>
        <p>Duis commodo sapien sed lorem aliquet gravida sed vitae odio. Nullam placerat mi non lectus tincidunt non
            condimentum felis porta. Ut sit amet justo risus. Cras faucibus tempus lorem.
        <p>Maecenas id libero mauris, eu consectetur nisi. Ut eu orci vel magna consequat pretium id a odio. Suspendisse
            arcu diam, varius a malesuada vestibulum, sollicitudin lobortis lectus.
    </div>

    <hr/>

    <div class="col col_3">
        <h3>Clothing Template</h3>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dolor nibh, varius at posuere et, ornare vitae
        nunc. Etiam at tellus et leo rutrum imperdiet sed sit amet sem.
    </div>
    <div class="col col_3">
        <h3>Cum sociis natoque </h3>
        Suspendisse pharetra, sapien sit amet faucibus luctus, sem odio molestie felis, quis eleifend lectus mi vitae
        dui. Nullam viverra mattis est, eget mollis eros suscipit et.
    </div>

    <div class="col col_3">
        <h3>Sed porttitor rhoncus</h3>
        Sed porttitor rhoncus libero, vulputate rutrum tellus convallis ac. Morbi dictum, metus ultrices auctor
        interdum, enim mauris posuere tellus, at tempus eros ante ac ipsum.
    </div>

    <hr/>

    <div class="col col_32">
        <h3>Pellentesque sed mi vitae</h3>
        Mauris consectetur, justo eu laoreet hendrerit, leo mauris consectetur turpis, id posuere metus tellus non
        mauris. Morbi quis risus eu dolor interdum pellentesque. Ut elit orci, faucibus a dictum nec, vulputate vel leo.
        Pellentesque sed mi vitae eros vehicula gravida vitae vitae lectus.
    </div>

    <div class="col col_3">
        <h3>Ut eu eros sed</h3>
        Phasellus vitae dui id metus mattis placerat sit amet et odio. Pellentesque vitae erat ante, sit amet adipiscing
        lectus.
    </div>

    <hr/>

    <div class="col col_4">
        <h3>Sed et tincidunt </h3>
        Mauris in nulla sapien, vitae blandit quam. In vel lacus vitae leo euismod dapibus sit amet et arcu. Sed et
        tincidunt eros.
    </div>
    <div class="col col_4">
        <h3>Aliquam malesuada</h3>
        Curabitur pellentesque arcu in elit faucibus nec sollicitudin ligula hendrerit. Sed sed felis ac tortor
        convallis accumsan.
    </div>
    <div class="col col_4">
        <h3>Suspendisse at nibh</h3>
        Aliquam malesuada sodales ante, sit amet molestie tellus tempus vel. Ut tincidunt arcu nisi, ac iaculis sem.
        Pellentesque vitae.
    </div>
    <div class="col col_4">
        <h3>Nulla congue urna</h3>
        Aliquam mollis, ipsum id rhoncus pharetra, erat nunc vestibulum turpis, ultricies viverra nulla felis adipiscing
        est.
    </div>

    <hr/>

    <div class="col col_4">
        <h3> Sed porttitor </h3>
        Nulla bibendum arcu nec est aliquet posuere. Sed porttitor rhoncus libero, vulputate rutrum tellus convallis ac
        enim.
    </div>
    <div class="col col_43">
        <h3>Aenean aliquam lectus sed</h3>
        Fusce non metus non libero sollicitudin pulvinar non nec libero. Ut magna elit, rhoncus id ullamcorper et,
        varius id purus. Proin ornare euismod neque at mollis. Donec gravida magna non risus bibendum fermentum et ut
        turpis. Nulla suscipit nunc nec urna ullamcorper bibendum. Maecenas non nibh purus, vitae volutpat metus. In
        hendrerit leo id arcu interdum imperdiet. Aenean aliquam lectus sed arcu auctor ornare.
    </div>

    <div class="clear"></div>
</div> <!-- END of main -->
{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>
        {% block title %}
        Base Page
        {% endblock %}
    </title>

    {% block css %}
    <link href="{% static 'css/tooplate_style.css' %}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/ddsmoothmenu.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/slimbox2.css' %}" type="text/css" media="screen"/>
    {% endblock%}

    {% block js%}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ddsmoothmenu.js' %}"></script>
    <script type="text/javascript">

        ddsmoothmenu.init({
            mainmenuid: "tooplate_menu", //menu DIV id
            orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
            classname: 'ddsmoothmenu', //class added to menu's outer DIV
            //customtheme: ["#1c5a80", "#18374a"],
            contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
        })

    </script>

    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/jquery.dualSlider.0.2.css' %}"/>
    <script type="text/javascript" src="{% static 'js/basket_scripts.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}" type="text/javascript"></script>

    <script src="{% static 'js/jquery.easing.1.3.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.timers-1.2.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.dualSlider.0.3.min.js' %}" type="text/javascript"></script>


    <script type="text/javascript">

            $(document).ready(function() {

                $("#carousel").dualSlider({
                    auto:false,
                    autoDelay: 6000,
                    easingCarousel: "swing",
                    easingDetails: "easeOutBack",
                    durationCarousel: 1000,
                    durationDetails: 600
                });

            });

    </script>
    <script type="text/JavaScript" src="{% static 'js/slimbox2.js' %}"></script>
    {% endblock %}

</head>
<body>
<div id="tooplate_wrapper">
    {% include 'mainapp/includes/inc_header.html' %}
    {% block main %}
    {% endblock %}
</div> <!-- END of wrapper -->


{% include 'mainapp/includes/inc_footer.html' %}
</body>
</html>

mainapp/templates/mainapp/checkout.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
{{ title|title }}
{% endblock %}
{% block main %}
<div id="tooplate_main"><span class="main_border main_border_t"></span><span class="main_border main_border_b"></span>
    <div class="col col_1">
        <h1>Checkout</h1>

        <h3>BILLING DETAILS </h3>
    </div>
    <div class="col col_2">
        <label>Enter your full name as it is on the credit card:<label>
            <input name="fullname" type="text" id="fullname" style="width:300px;"/>
            <label>Address:</label>
            <input name="address" type="text" id="address" style="width:300px;"/>
            <label>City:</label>
            <input name="city" type="text" id="city" style="width:300px;"/>
            <label>Country:</label>
            <input name="country" type="text" id="country" style="width:300px;"/>

    </div>

    <div class="col col_2">
        <label>E-MAIL</label>
        <input name="email" type="text" id="email" style="width:300px;"/>
        <label>PHONE</label>
        <span style="font-size:10px; display: block;">Please, specify your reachable phone number. YOU MAY BE GIVEN A CALL TO VERIFY AND COMPLETE THE ORDER.</span>
        <input name="phone" type="text" id="phone" style="width:300px;"/>
    </div>

    <hr/>

    <div class="col col_1">
        <h3>SHOPPING CARD</h3>
        <h4>TOTAL: <strong>$140</strong></h4>
        <p><input type="checkbox"/>I have accepted the Terms of Use.</p>
        <p><a href="#"><img src="images/1311260370_paypal-straight.png" alt="paypal"/></a>&nbsp;Recommended if you have
            a PayPal account. Fastest delivery time.</p>
    </div>
    <div class="clear"></div>
</div> <!-- END of main -->
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block title %}
{{ title|title }}
{% endblock %}
{% block main %}
<div id="tooplate_slider" class="section_content"><span class="frame"></span>
    <div id="carousel">
        <div class="panel">

            <div class="details_wrapper">

                <div class="details">
                    {% for product in new_products %}
                    <div class="detail">
                        <h2>{{product.name}}</h2>
                        <p>{{product.short_desc}}</p>
                        <a href="{% url 'products:productdetail' product.id %}" title="Подробнее" class="slider_more">Подробнее</a>
                    </div><!-- /detail -->
                    {% endfor %}

                </div><!-- /details -->

            </div><!-- /details_wrapper -->

        </div><!-- /panel -->

        <a href="javascript:void(0);" class="previous" title="Previous">Назад</a>
        <a href="javascript:void(0);" class="next" title="Next">Вперёд</a>

        <div id="slider-image-frame">
            <div class="backgrounds">
                {% for product in new_products %}
                <div class="item item_1">
                    <img src="{{product.image|media_folder_products}}" alt="{{product.name}}"/>
                </div><!-- /item -->
                {% endfor %}

            </div><!-- /backgrounds -->
        </div>
    </div>
    <div class="clear"></div>
</div> <!-- END of slider -->
<div id="tooplate_main"><span class="main_border main_border_t"></span><span class="main_border main_border_b"></span>
    <div class="product">
        <h1>Новинки</h1>
        {% for product in new_products %}
        <div class="product_box">
            <div class="img_box"><span></span>
                <a href="{% url 'products:productdetail' product.id %}"><img src="{{ product.image|media_folder_products }}" alt="{{ product.short.desc }}"
                                                       height="148px" width="160px"/></a>
            </div>
            <h2><a href="{% url 'products:productdetail' product.id %}">{{ product.name }}</a></h2>
            <p class="price">${{ product.price }}</p>
        </div>
        {% endfor %}
    </div>

    <div class="clear h20"></div>
    <hr/>
    <div class="clear h10"></div>

    <div class="product">
        <h1>Популярное</h1>
        {% for product in popular_product %}
        <div class="product_box">
            <div class="img_box"><span></span>
                <a href="#"><img src="{{ product.image.url }}" alt="image" height="148px" width="160px"/></a>
            </div>
            <h2><a href="#">{{ product.name|lower }}</a></h2>
            <p class="price">${{ product.price }}</p>
        </div>
        {% endfor %}
    </div>

    <div class="clear"></div>
</div> <!-- END of main -->
{% endblock %}

mainapp/templates/mainapp/productdetail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block title %}
{{ title|title }}
{% endblock %}
{% block main %}
<div id="tooplate_main"><span class="main_border main_border_t"></span><span class="main_border main_border_b"></span>

    <div class="product">
        <div class="col col_2 product_preview">
            <a rel="lightbox" href="/media/{{ product.image.url }}"><img src="{{product.image|media_folder_products}}"
                                                                         class="left" alt="{{product.name}}" /></a>
            <ul class="nobullet">
                <li><a rel="lightbox" href="/media/{{product.image.url}}"><img src="{{product.image|media_folder_products}}"
                                                                                 class="right" alt="{{product.name}}"/></a></li>
                <li><a rel="lightbox" href="/media/{{product.image.url}}"><img src="{{product.image|media_folder_products}}"
                                                                                 class="right" alt="{{product.name}}"/></a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="col col_2 product_detail">
            <h1>{{ product.name}}</h1>
            <p><em>{{product.short_desc}}</em></p>
            <p>{{product.description}}</p>
            <div class="clear h20"></div>
            <p class="price">${{product.price}}<span>Доступность: <strong> {% if product.quantity > 1 %} В наличии {% else %} Нет в наличии {% endif %}</strong></span></p>
            <div class="clear h20"></div>
            <p class="add_to_cart">На складе: <strong>{{product.quantity}}</strong></p>
            <a href="{% url 'basket:add' product.id %}" class="button left">Добавить в корзину</a>
        </div>
        <div class="clear"></div>
    </div>

    <hr/>

    <div class="product">
        <h2>Рекомендуемые товары</h2>
        {% for product in recommend_products %}
        <div class="product_box">
            <div class="img_box"><span></span>
                <a href="{% url 'products:productdetail' product.id %}"><img src="/media/{{product.image}}" alt="{{product.name}}"/></a>
            </div>
            <h2><a href="{% url 'products:productdetail' product.id %}">{{product.name|upper}}</a></h2>
            <p class="price">${{product.price}}</p>
        </div>
        {% endfor %}
    </div>


    <div class="clear"></div>
</div> <!-- END of main -->
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block title %}
{{ title|title }}
{% endblock %}
{% block main %}
<div id="tooplate_main"><span class="main_border main_border_t"></span><span class="main_border main_border_b"></span>
    <div class="product">
        <h1>{{current_category.name}}</h1>
        {% for product in products %}
        <div class="product_box">
            <div class="img_box"><span></span>
                <a href="{% url 'products:productdetail' product.id %}"><img src="{{ product.image|media_folder_products }}"
                                                                             alt="{{ product.short_desc}}"
                                                                             height="148px" width="170px"/></a>
            </div>
            <h2><a href="{{ product.image.url }}">{{ product.name }}</a></h2>
            <p class="price">${{ product.price }}</p>
        </div>
        {% endfor %}
    </div>

    <hr/>

    <div class="pagging">
        <ul>
            {% if products.has_previous %}
            <li><a href="{% url 'products:page' current_category.pk products.previous_page_number %}" target="_parent">Назад</a>
            </li>
            {% endif %}
            {% for i in page_range|default_if_none:products.paginator.get_elided_page_range %}
                {% if products.number == i %}
                <li><a href="{% url 'products:page' current_category.pk i %}" target="_parent" class="selected">{{ i }}</a></li>
                </li>
                {% else %}
                    {% if i == products.paginator.ELLIPSIS %}
                    <li><a href="#" target="_parent">{{ i }}</a></li>
                    {% else %}
                    <li><a href="{% url 'products:page' current_category.pk i %}" target="_parent">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li><a href="{% url 'products:page' current_category.pk products.next_page_number %}" target="_parent">Вперёд</a>
            </li>
            {% endif %}
        </ul>
        <div class="clear"></div>
    </div>


    <div class="clear"></div>
</div> <!-- END of main -->
{% endblock %}

mainapp/templates/mainapp/shoppingcart.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load mainapp_extras %}
{% block title %}
{{ title|title }}
{% endblock %}
{% block main %}
<div id="tooplate_main"><span class="main_border main_border_t"></span><span class="main_border main_border_b"></span>

    <div id="content">
        <h1>Товары в корзине</h1>

        <table width="580px" cols="0" cellspacing="0" cellpadding="5">
            <tr bgcolor="#ddd">
                <th width="220" align="left">Изображение</th>
                <th width="180" align="left">Название</th>
                <th width="100" align="center">Кол-во</th>
                <th width="60" align="right">Цена</th>
                <th width="60" align="right">Сумма</th>
                <th width="90"></th>

            </tr>
            {% for product in products %}

            <tr>
                <td><a href="{% url 'products:productdetail' product.id %}"><img src="{{ product.image|media_folder_products }}" alt="{{product.name}}" height="70px"/></a></td>
                <td><a href="{% url 'products:productdetail' product.id %}">{{ product.name|upper }}</a></td>
                <td align="center"><input type="text" value="1"
                                          style="width: 20px; text-align: right"/></td>
                <td align="right">${{ product.price }}</td>
                <td align="right">${% multiply product.quantity product.price %}</td>
                <td align="center"><a href="#"><img src="{% static 'img/remove.png' %}" alt="remove"/><br/>Удалить</a>
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="3" style="background: url({% static 'img/tooplate_h2.png' %}) repeat" align="right"
                    height="30px">Have
                    you modified your basket? Please click here to <a
                            href="{% url 'shoppingcart' %}"><strong>Update</strong></a>&nbsp;&nbsp;
                </td>
                <td align="right" style="background: url({% static 'img/tooplate_h2.png' %}) repeat; font-weight:bold">
                    Сумма корзины
                </td>
                <td align="right" style="background: url({% static 'img/tooplate_h2.png' %}) repeat; font-weight:bold">
                    $140
                </td>
                <td style="background: url({% static 'img/tooplate_h2.png' %}) repeat; font-weight:bold"></td>
            </tr>
        </table>
        <p class="right"><a href="checkout.html" class="button">checkout</a></p>
    </div>

    {% include 'mainapp/includes/inc_popular_products.html' %}
    <div class="clear"></div>
</div> <!-- END of main -->
{% endblock %}